package sdp.strategy;

public enum GameState {
	PLAYING, THEY_HAVE_BALL, WE_HAVE_BALL, STANDING_BY, RESETTING, TRIED_TO_SCORE, DEFENTING_PENALTY, BALL_IN_CORNER, KICKING_PENALTY, DEFENDING_PENALTY, NO_CLEAR_SHOT, SCRUM
}